### ISSUE TITLE
При установке 404

### ISSUE THREAD

**Issue by letnab** [akaLexa/AnotherProjectERP#10]
На главной странице, при выборе билда, всегда выскакивает Error 404
centos 6.8
Apache/2.4.18 (Red Hat) PHP/5.6.25
mysql  Ver 14.14 Distrib 5.6.34, for Linux (x86_64) using  EditLine wrapper

**Comment by akaLexa** [comment]
в снифере (вкладка network) на какой адрес уходит XHR?

**Comment by letnab** [comment]
Request URL:http://10.10.1.69/page/install/GetBuildInfo
Request Method:POST
Status Code:404 Not Found
Remote Address:10.10.1.23:80
Response Headers
view source
Connection:Keep-Alive
Content-Length:223
Content-Type:text/html; charset=iso-8859-1
Date:Fri, 24 Mar 2017 04:38:48 GMT
Keep-Alive:timeout=5, max=100
Server:Apache/2.4.18 (Red Hat) PHP/5.6.25
Request Headers
view source
Accept:*/*
Accept-Encoding:gzip, deflate
Accept-Language:ru-RU,ru;q=0.8,en-US;q=0.6,en;q=0.4
Connection:keep-alive
Content-Length:18
Content-Type:application/x-www-form-urlencoded; charset=UTF-8
Cookie:PHPSESSID=m9evf4vnqs3fgo2oq2p0mp9sp5
Host:10.10.1.69
Origin:http://10.10.1.69
Referer:http://10.10.1.69/
User-Agent:Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36
X-Requested-With:XMLHttpRequest
Form Data
view source
view URL encoded
choseBuild:install

**Comment by akaLexa** [comment]
а если пройти по адресу [http://10.10.1.69/page/install/GetBuildInfo](http://10.10.1.69/page/install/GetBuildInfo) что получится? ощущение такое, что неадекватно работает modRewrite. Попробуйте через имя, а не IP.

**Comment by letnab** [comment]
по имени и по ip результат тот же
Not Found

The requested URL /page/install/GetBuildInfo was not found on this server.

**Comment by letnab** [comment]
поменял в конфиге AllowOverride None на AllowOverride All есть установка

**Comment by letnab** [comment]
При выборе билда install 
Внимание
У выбранного билда отсутствуют параметры установки. Это не ошибка. Возможно, просто не предусмотрено устанавливать выбранный билд, но он служит как механизм, например, билд Install. Пожалуйста, выберите **дял** установки другой билд.

при выборе erp появляется поля для подключения к mysql

`SQLSTATE[21S01]: Insert value list does not match column list: 1136 Column count doesn't match value count at row 1, log text: INSERT INTO tbl_project VALUES (1, 'Тестовый проект', 1, 1, '2016-12-10 11:34:09', '<p>asdasd!!</p>', '0');`
при это таблицы в mysql созданы

**Comment by akaLexa** [comment]
принято. проверю

**Comment by akaLexa** [comment]
Поправил, нужно скачать файлик [https://github.com/akaLexa/AnotherProjectERP/blob/master/build/erp/SQL/4.03.tbl_project.sql](https://github.com/akaLexa/AnotherProjectERP/blob/master/build/erp/SQL/4.03.tbl_project.sql)  снести все базы, что были установлены и поставить заново.
