### ISSUE TITLE
Ошибка при добавлении групп

### ISSUE THREAD

**Issue by letnab** [akaLexa/AnotherProjectERP#12]
в файле Update 4.04.tbl_user_groups.sql ошибка. 
нужно не (1, 'IT отдел') а (null, 'IT отдел', 1)
При этом скрипт отрабатывает,но в таблицу ничего не прилетает. 
и в конце Неизвестная ошибка, скорее всего, недоступен сервер баз данных

**Comment by akaLexa** [comment]
да, спасибо, уже вкурсе. пересобираю весь инстал

**Comment by letnab** [comment]
окей.

**Comment by akaLexa** [comment]
[https://github.com/akaLexa/AnotherProjectERP/blob/master/build/erp/SQL/4.04.tbl_user_groups.sql](https://github.com/akaLexa/AnotherProjectERP/blob/master/build/erp/SQL/4.04.tbl_user_groups.sql) нужно перекачать и запустить инсталку

**Comment by letnab** [comment]
Билд установился
